---
title: "Cyclistic Ride Behavior Analysis"
author: "Thien"
date: "2025-12-10"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Load library
```{r}
install.packages("tidyverse")
install.packages("skimr")
install.packages("janitor")
```

```{r}
library(tidyverse)
library(skimr)
library(janitor)
```

#Load datasets
```{r}
data_202307 <- read.csv("data/202307-divvy-tripdata.csv")
data_202308 <- read.csv("data/202308-divvy-tripdata.csv")
data_202309 <- read.csv("data/202309-divvy-tripdata.csv")
data_202310 <- read.csv("data/202310-divvy-tripdata.csv")
data_202311 <- read.csv("data/202311-divvy-tripdata.csv")
data_202312 <- read.csv("data/202312-divvy-tripdata.csv")
data_202401 <- read.csv("data/202401-divvy-tripdata.csv")
data_202402 <- read.csv("data/202402-divvy-tripdata.csv")
data_202403 <- read.csv("data/202403-divvy-tripdata.csv")
data_202404 <- read.csv("data/202404-divvy-tripdata.csv")
data_202405 <- read.csv("data/202405-divvy-tripdata.csv")
data_202406 <- read.csv("data/202406-divvy-tripdata.csv")
```

#Combine all dataset into one
```{r}

all_trips <- bind_rows(
  data_202307,
  data_202308,
  data_202309,
  data_202310,
  data_202311,
  data_202312,
  data_202401,
  data_202402,
  data_202403,
  data_202404,
  data_202405,
  data_202406
)
```

```{r}
summary(all_trips)
```
```{r}
skim_without_charts(all_trips)
```


```{r}
#Remove bad rows in started_at and ended_at
all_trips <- all_trips %>% 
  filter(!is.na(started_at), !is.na(ended_at)) %>% 
  mutate(ride_length_min = as.numeric(difftime(ended_at, started_at, units = "mins")),
         ride_length_min = round(ride_length_min, 2) ) %>% 
  filter(ride_length_min > 0)  # remove negative or zero duration
```

```{r}
#Rows where these are missing or obviously wrong should be removed
all_trips<- all_trips %>% 
  filter(
    !is.na(start_lat), !is.na(start_lng),
    !is.na(end_lat),   !is.na(end_lng)
  )
```


```{r}
all_trips<- all_trips %>% 
  mutate(
    start_station_name = na_if(trimws(start_station_name), ""),
    end_station_name   = na_if(trimws(end_station_name), "")
  )
```

```{r}
# lookup for start stations
start_lookup <- all_trips %>% 
  filter(!is.na(start_station_name)) %>% 
  count(start_lat, start_lng, start_station_name, sort = TRUE) %>% 
  group_by(start_lat, start_lng) %>% 
  slice_max(n, n = 1, with_ties = FALSE) %>% 
  ungroup() %>% 
  select(start_lat, start_lng, start_station_name)

# lookup for end stations
end_lookup <- all_trips %>% 
  filter(!is.na(end_station_name)) %>% 
  count(end_lat, end_lng, end_station_name, sort = TRUE) %>% 
  group_by(end_lat, end_lng) %>% 
  slice_max(n, n = 1, with_ties = FALSE) %>% 
  ungroup() %>% 
  select(end_lat, end_lng, end_station_name)
```

```{r}
# fill start_station_name
all_trips<- all_trips%>% 
  left_join(start_lookup,
            by = c("start_lat", "start_lng"),
            suffix = c("", "_lookup")) %>% 
  mutate(
    start_station_name = coalesce(start_station_name, start_station_name_lookup)
  ) %>% 
  select(-start_station_name_lookup)

# fill end_station_name
all_trips<- all_trips %>% 
  left_join(end_lookup,
            by = c("end_lat", "end_lng"),
            suffix = c("", "_lookup")) %>% 
  mutate(
    end_station_name = coalesce(end_station_name, end_station_name_lookup)
  ) %>% 
  select(-end_station_name_lookup)
```

```{r}
colSums(is.na(all_trips[c("start_station_name", "end_station_name")]))
```


```{r}
skim_without_charts(all_trips)
```
```{r}
all_trips <- all_trips %>% 
  mutate(
    started_at = ymd_hms(started_at, tz = "America/Chicago"),
    ended_at   = ymd_hms(ended_at,   tz = "America/Chicago")
  )
```

```{r}
all_trips <- all_trips %>% 
  mutate(
    # basic calendar fields
    ride_date    = as.Date(started_at),
    ride_hour    = hour(started_at),                           # 0–23
    ride_weekday = wday(started_at, label = TRUE,              # Mon, Tue, ...
                         abbr  = FALSE, week_start = 1),
    ride_month   = month(started_at, label = TRUE, abbr = TRUE), # Jan, Feb…
    ride_year    = year(started_at),

    # weekend flag (TRUE for Sat / Sun)
    is_weekend   = wday(started_at) %in% c(1, 7),              # 1 = Sun, 7 = Sat

    # season based on month (Northern hemisphere)
    season = case_when(
      month(started_at) %in% c(12, 1, 2) ~ "Winter",
      month(started_at) %in% c(3, 4, 5) ~ "Spring",
      month(started_at) %in% c(6, 7, 8) ~ "Summer",
      TRUE                              ~ "Fall"
    )
  )
```


